# common mixin
common: &common
    server: ""
    debug: false

    # limits
    userLimit: 5
    diskFreeUpdateLimit: 3221225472

    # TODO: use in reports
    dateTimeFormat: 'YYYY-MM-DD HH:mm:ss.SSS'

    # modules
    defaultModule      : dashboards
    adminDefaultModule : settings

    # paths
    root: /
    resourcePath  : locale/__lng__/__ns__.json
    templatesPath : /scripts/templates

    # modules configuration
    reports:
        # show confirmation dialog on report/widget
        # edit canceling (only by "Cancel" & "X" buttons)
        confirmCancel    : false
        maxTreeDepth     : 5

        grid:
          cols         : 3
          margin       : 3
          resizeDelay  : 500

        widget:
          height: 470
          min: {x: 1, y: 1}
          max: {x: 3, y: 2}
          padding:
            top: 65 # 45+20

    diagnostic:
      delayRefresh: 15000

# local machine only
development: &development
    << : *common
    debug: true
    env: development
    server: "https://v-tavadov-current"

# karma and other tests
test:
    << : *common

    env: test
    login: officer
    password: xxXX1234

    # overide
    resourcePath: base/@build_test/locale/__lng__/__ns__.json
    templatesPath: /base/@build_test/scripts/templates

    # audit
    audit_date: 12-08-2014
    audit_entity_type: Dashboard
    audit_user_id: 21
    audit_operation: view

# also for stands
production:
    env: production
    << : *common
